# deploy repo to cloud
name: Push to Azure Container Registry
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set small sha variable
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Check variable
        run: |
          echo "SHA short: ${{ env.sha_short }}"

      - name: Set up Node.js

        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust to your Node.js version

      - name: Install dependencies in the cloned repository
        working-directory: ./client
        run: npm install

      #   - name: Remove current env if it exists
      #     working-directory: ./client
      #     run: |
      #       if [ -f .env ]; then
      #         rm .env
      #       fi

      #   - name: Create .env file for client
      #     working-directory: ./client
      #     run: echo "VITE_API_PATH=''" > .env

      - name: Run npm build in the cloned repository
        working-directory: ./client
        run: npm run build # Adjust to your build command
        env:
          CI: false

      - name: Remove existing dist folder in server directory
        run: rm -rf server/dist

      - name: Remove existing assets folder in server directory
        run: rm -rf server/assets

      - name: Copy dist folder from client to server directory
        run: cp -r client/dist server

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build, tag, and push the image to Amazon ECR
        working-directory: ./server
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: runclub-tv
          IMAGE_TAG: latest
        run: |
          # Build a docker container and push it to ECR 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
